### ISSUE TITLE
Daemon Error: Service Failed to Start

### ISSUE THREAD

**Issue by shadyslim2018** [2nv2u/gnome-shell-extension-syncthing-indicator#16]
The only way to get syncthing tray working is to stop 'syncthing@username.service' then start it again when the syncthing tray is working.

**Comment by 2nv2u** [comment]
I'll see if I can detect if a system wide service is running, currently that's not supported

**Comment by 2nv2u** [comment]
This should be fixed, can you test it?

**Comment by shadyslim2018** [comment]
I'm afraid it's still the same, but it's no bother. I just stop and disable syncthing@username.service and enable Service on the synching indicator.
