### ISSUE TITLE
"Connection Error" again and again

### ISSUE THREAD

**Issue by alfredo-igm** [2nv2u/gnome-shell-extension-syncthing-indicator#50]
On OpenSuse 15.6.
It was working fine but when i change user password, errors started.
To change again to last password didn't fix it.
Uninstall extension without problems but install it again gives "error" but icon on upper bar is shown... and "Connection error" is shown again.
Debug shows:
(gnome-shell:5094): GNOME Shell-WARNING **: 17:16:37.070: error: Syncthing Indicator: connection-error
GNOME Shell-Message: 17:16:37.136: GNOME Shell started at Tue Mar 11 2025 17:16:34 GMT+0100 (hora estándar de Europa central)
GNOME Shell-Message: 17:16:37.136: Registering session with GDM

(gnome-shell:5094): GNOME Shell-CRITICAL **: 17:16:37.147: syncthing-indicator-manager: Connection status error null GET:/rest/system/error 0

(gnome-shell:5094): GNOME Shell-CRITICAL **: 17:16:37.148: syncthing-indicator: connection-error {
    "type": "Connection status error",
    "message": "null - GET:/rest/system/error"
}

(gnome-shell:5094): GNOME Shell-WARNING **: 17:16:37.148: error: Syncthing Indicator: connection-error
(gnome-shell:5094): GNOME Shell-DEBUG: 17:17:04.780: syncthing-indicator-manager: calling systemd is-enabled false Array [
(gnome-shell:5094): GNOME Shell-DEBUG: 17:17:04.797: syncthing-indicator-manager: calling systemd is-enabled true Array [
(gnome-shell:5094): GNOME Shell-DEBUG: 17:17:04.819: syncthing-indicator-manager: calling systemd is-active true Array [
(gnome-shell:5094): GNOME Shell-DEBUG: 17:17:04.820: syncthing-indicator-manager: opening connection GET:/rest/system/error

(gnome-shell:5094): GNOME Shell-CRITICAL **: 17:17:05.768: syncthing-indicator-manager: Connection status error null GET:/rest/system/error 0

(gnome-shell:5094): GNOME Shell-CRITICAL **: 17:17:05.771: syncthing-indicator: connection-error {
    "type": "Connection status error",
    "message": "null - GET:/rest/system/error"

On command line :
$ ps aux | grep syncthing
user  28670  0.0  0.2 1249344 21248 ?       Ssl  17:14   0:00 /usr/bin/syncthing serve --no-browser --no-restart --logflags=0
user  28679  1.3  0.5 1251520 42676 ?       SNl  17:14   0:12 /usr/bin/syncthing serve --no-browser --no-restart --logflags=0

I dont know if duplicate server process is normal. When I try to kill one, both of them close.
As user o root there is no "systemctl status syncthing" so I am quite sure it's just launch, as ps indicates, as simple user.
Any idea to solve it ?

**Comment by 2nv2u** [comment]
Can you try to use the systemd calls to see what's going on?
https://docs.syncthing.net/users/autostart.html#using-systemd

**Comment by 2nv2u** [comment]
A lot has changed in the way this works, I hope this is fixed now, can you test it?

**Comment by alfredo-igm** [comment]
I've tested service running as system service and still fails.
Now i am running as user service and same error persists.
From "sudo journalct -f "  repeats next message each 20 seconds:

abr 01 11:09:35 IGM-ALFREDO-LIN gnome-shell[3952]: syncthing-indicator-manager: Connection status error null GET:/rest/system/error 0
abr 01 11:09:35 IGM-ALFREDO-LIN gnome-shell[3952]: syncthing-indicator: connection-error {
                                                       "type": "Connection status error",
                                                       "message": "null - GET:/rest/system/error"
                                                   }
abr 01 11:09:35 IGM-ALFREDO-LIN gnome-shell[3952]: error: Syncthing Indicator: connection-error

But Syncthing is working fine. Files and folders are synchronized against others computers and mobiles.
As user :

alfredo@IGM-ALFREDO-LIN:~/.config/systemd/user> systemctl --user status syncthing.service 
● syncthing.service - Syncthing - Open Source Continuous File Synchronization
     Loaded: loaded (/home/alfredo/.config/systemd/user/syncthing.service; enabled; preset: disabled)
     Active: active (running) since Tue 2025-04-01 11:06:14 CEST; 6min ago
       Docs: man:syncthing(1)
   Main PID: 14581 (syncthing)
      Tasks: 19 (limit: 4915)
        CPU: 5.463s
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/syncthing.service
             ├─14581 /usr/bin/syncthing serve --no-browser --no-restart --logflags=0
             └─14591 /usr/bin/syncthing serve --no-browser --no-restart --logflags=0

Option "Ignore permissions" changes nothing.
Daemon has been restarted after each change and any change has been done one by one in order to guess which one could be the right one.
Sorry.
Nowadays "https://127.0.0.1:8384/"  at web-browser is my the only way to know that my Syncthing is up & running.
It must be my computer the only one where this plugin does not work.
Thank you.

**Comment by 2nv2u** [comment]
It look like it cannot resolve the config (API key & URI).
Can you run this command (need to use wayland) to see if you see anything config related coming by?

`clear && export G_MESSAGES_DEBUG=all && dbus-run-session -- gnome-shell --nested --wayland | grep syncthing-indicator`

**Comment by alfredo-igm** [comment]
On Wayland:

dbus-daemon[19686]: [session uid=1000 pid=19686] Activating service name='org.gtk.vfs.Daemon' requested by ':1.0' (uid=1000 pid=19687 comm="gnome-shell --nested --wayland ")
dbus-daemon[19706]: writing oom_score_adj error: Permission denied
dbus-daemon[19686]: [session uid=1000 pid=19686] Successfully activated service 'org.gtk.vfs.Daemon'
fusermount3: failed to access mountpoint /run/user/1000/gvfs: Permission denied
libmutter-Message: 13:02:00.343: Running GNOME Shell (using mutter 45.3) as a Wayland display server
** Message: 13:02:00.415: Obtained a high priority EGL context
** Message: 13:02:00.417: Obtained a high priority EGL context
dbus-daemon[19686]: [session uid=1000 pid=19686] Activating service name='org.a11y.Bus' requested by ':1.2' (uid=1000 pid=19687 comm="gnome-shell --nested --wayland ")
dbus-daemon[19729]: writing oom_score_adj error: Permission denied
dbus-daemon[19686]: [session uid=1000 pid=19686] Successfully activated service 'org.a11y.Bus'
libmutter-Message: 13:02:00.457: Using public X11 display :2, (using :3 for managed services)

(gnome-shell:19687): libmutter-WARNING **: 13:02:00.457: WL: unable to lock lockfile /run/user/1000/wayland-0.lock, maybe another compositor is running

libmutter-Message: 13:02:00.457: Using Wayland display name 'wayland-1'
Window manager warning: Failed to set environment variable GNOME_SETUP_DISPLAY for gnome-session: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.gnome.SessionManager" does not exist
Window manager warning: Failed to set environment variable DISPLAY for gnome-session: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.gnome.SessionManager" does not exist
Window manager warning: Failed to set environment variable XAUTHORITY for gnome-session: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.gnome.SessionManager" does not exist
Window manager warning: Failed to set environment variable WAYLAND_DISPLAY for gnome-session: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.gnome.SessionManager" does not exist
dbus-daemon[19736]: Activating service name='org.a11y.atspi.Registry' requested by ':1.0' (uid=1000 pid=19687 comm="gnome-shell --nested --wayland ")
dbus-daemon[19739]: writing oom_score_adj error: Permission denied
dbus-daemon[19736]: Successfully activated service 'org.a11y.atspi.Registry'
GNOME Shell-Message: 13:02:00.993: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
GNOME Shell-Message: 13:02:00.993: Will monitor session 2
dbus-daemon[19686]: [session uid=1000 pid=19686] Activating service name='org.gnome.Shell.Screencast' requested by ':1.0' (uid=1000 pid=19687 comm="gnome-shell --nested --wayland ")
dbus-daemon[19748]: writing oom_score_adj error: Permission denied
dbus-daemon[19686]: [session uid=1000 pid=19686] Activating service name='org.freedesktop.impl.portal.PermissionStore' requested by ':1.0' (uid=1000 pid=19687 comm="gnome-shell --nested --wayland ")
dbus-daemon[19758]: writing oom_score_adj error: Permission denied
dbus-daemon[19686]: [session uid=1000 pid=19686] Activating service name='org.gnome.Shell.CalendarServer' requested by ':1.0' (uid=1000 pid=19687 comm="gnome-shell --nested --wayland ")
dbus-daemon[19761]: writing oom_score_adj error: Permission denied
(/usr/lib/xdg-permission-store:19758): GLib-GIO-DEBUG: 13:02:01.077: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
(/usr/lib/xdg-permission-store:19758): xdg-desktop-portal-DEBUG: 13:02:01.078: Starting permission store
dbus-daemon[19686]: [session uid=1000 pid=19686] Successfully activated service 'org.freedesktop.impl.portal.PermissionStore'
dbus-daemon[19686]: [session uid=1000 pid=19686] Activating service name='org.gnome.evolution.dataserver.Sources5' requested by ':1.8' (uid=1000 pid=19761 comm="/usr/lib/gnome-shell/gnome-shell-calendar-server ")
dbus-daemon[19773]: writing oom_score_adj error: Permission denied
dbus-daemon[19686]: [session uid=1000 pid=19686] Activating service name='org.gnome.Shell.Notifications' requested by ':1.0' (uid=1000 pid=19687 comm="gnome-shell --nested --wayland ")
GNOME Shell-Message: 13:02:01.265: Extension apps-menu@gnome-shell-extensions.gcampax.github.com already installed in /home/alfredo/.local/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com will not be loaded
GNOME Shell-Message: 13:02:01.265: Extension launch-new-instance@gnome-shell-extensions.gcampax.github.com already installed in /home/alfredo/.local/share/gnome-shell/extensions/launch-new-instance@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/launch-new-instance@gnome-shell-extensions.gcampax.github.com will not be loaded
GNOME Shell-Message: 13:02:01.266: Extension places-menu@gnome-shell-extensions.gcampax.github.com already installed in /home/alfredo/.local/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com will not be loaded
GNOME Shell-Message: 13:02:01.266: Extension window-list@gnome-shell-extensions.gcampax.github.com already installed in /home/alfredo/.local/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com will not be loaded
GNOME Shell-Message: 13:02:01.266: Extension workspace-indicator@gnome-shell-extensions.gcampax.github.com already installed in /home/alfredo/.local/share/gnome-shell/extensions/workspace-indicator@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/workspace-indicator@gnome-shell-extensions.gcampax.github.com will not be loaded
dbus-daemon[19811]: writing oom_score_adj error: Permission denied
dbus-daemon[19686]: [session uid=1000 pid=19686] Activating service name='org.gnome.OnlineAccounts' requested by ':1.9' (uid=1000 pid=19773 comm="/usr/lib/evolution-data-server/evolution-source-re")
dbus-daemon[19820]: writing oom_score_adj error: Permission denied
dbus-daemon[19686]: [session uid=1000 pid=19686] Successfully activated service 'org.gnome.evolution.dataserver.Sources5'
dbus-daemon[19686]: [session uid=1000 pid=19686] Successfully activated service 'org.gnome.Shell.CalendarServer'
dbus-daemon[19686]: [session uid=1000 pid=19686] Successfully activated service 'org.gnome.Shell.Screencast'
dbus-daemon[19686]: [session uid=1000 pid=19686] Activating service name='org.gnome.evolution.dataserver.Calendar8' requested by ':1.8' (uid=1000 pid=19761 comm="/usr/lib/gnome-shell/gnome-shell-calendar-server ")
dbus-daemon[19686]: [session uid=1000 pid=19686] Successfully activated service 'org.gnome.Shell.Notifications'
dbus-daemon[19848]: writing oom_score_adj error: Permission denied
goa-daemon-Message: 13:02:01.475: goa-daemon version 3.48.0 starting
dbus-daemon[19686]: [session uid=1000 pid=19686] Activating service name='org.gnome.Identity' requested by ':1.12' (uid=1000 pid=19820 comm="/usr/lib/goa-daemon ")
dbus-daemon[19861]: writing oom_score_adj error: Permission denied
dbus-daemon[19686]: [session uid=1000 pid=19686] Successfully activated service 'org.gnome.OnlineAccounts'
dbus-daemon[19686]: [session uid=1000 pid=19686] Successfully activated service 'org.gnome.Identity'

(process:19861): libgoaidentity-WARNING **: 13:02:01.512: GoaKerberosIdentityManager: Using polling for change notification for credential cache type 'KEYRING'
dbus-daemon[19686]: [session uid=1000 pid=19686] Successfully activated service 'org.gnome.evolution.dataserver.Calendar8'
dbus-daemon[19686]: [session uid=1000 pid=19686] Activating service name='org.gnome.evolution.dataserver.AddressBook10' requested by ':1.11' (uid=1000 pid=19848 comm="/usr/lib/evolution-data-server/evolution-calendar-")
dbus-daemon[19874]: writing oom_score_adj error: Permission denied
dbus-daemon[19686]: [session uid=1000 pid=19686] Successfully activated service 'org.gnome.evolution.dataserver.AddressBook10'
GNOME Shell-Message: 13:02:01.718: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
dbus-daemon[19686]: [session uid=1000 pid=19686] Activating service name='org.gtk.vfs.UDisks2VolumeMonitor' requested by ':1.0' (uid=1000 pid=19687 comm="gnome-shell --nested --wayland ")
dbus-daemon[19908]: writing oom_score_adj error: Permission denied
dbus-daemon[19686]: [session uid=1000 pid=19686] Successfully activated service 'org.gtk.vfs.UDisks2VolumeMonitor'
dbus-daemon[19686]: [session uid=1000 pid=19686] Activating service name='org.gtk.vfs.AfcVolumeMonitor' requested by ':1.0' (uid=1000 pid=19687 comm="gnome-shell --nested --wayland ")
dbus-daemon[19944]: writing oom_score_adj error: Permission denied
dbus-daemon[19686]: [session uid=1000 pid=19686] Successfully activated service 'org.gtk.vfs.AfcVolumeMonitor'
dbus-daemon[19686]: [session uid=1000 pid=19686] Activating service name='org.gtk.vfs.GoaVolumeMonitor' requested by ':1.0' (uid=1000 pid=19687 comm="gnome-shell --nested --wayland ")
dbus-daemon[19951]: writing oom_score_adj error: Permission denied
dbus-daemon[19686]: [session uid=1000 pid=19686] Successfully activated service 'org.gtk.vfs.GoaVolumeMonitor'
dbus-daemon[19686]: [session uid=1000 pid=19686] Activating service name='org.gtk.vfs.MTPVolumeMonitor' requested by ':1.0' (uid=1000 pid=19687 comm="gnome-shell --nested --wayland ")
dbus-daemon[19957]: writing oom_score_adj error: Permission denied
dbus-daemon[19686]: [session uid=1000 pid=19686] Successfully activated service 'org.gtk.vfs.MTPVolumeMonitor'
dbus-daemon[19686]: [session uid=1000 pid=19686] Activating service name='org.gtk.vfs.GPhoto2VolumeMonitor' requested by ':1.0' (uid=1000 pid=19687 comm="gnome-shell --nested --wayland ")
dbus-daemon[19963]: writing oom_score_adj error: Permission denied
dbus-daemon[19686]: [session uid=1000 pid=19686] Successfully activated service 'org.gtk.vfs.GPhoto2VolumeMonitor'
GNOME Shell-Message: 13:02:01.926: Failed to register AuthenticationAgent
GNOME Shell-Message: 13:02:02.574: [system-monitor-next] applet enable from /home/alfredo/.local/share/gnome-shell/extensions/system-monitor-next@paradoxxx.zero.gmail.com

(gnome-shell:19687): GNOME Shell-CRITICAL **: 13:02:02.732: [system-monitor-next] Invalid thermal sensor label: "" (valid choices: acpitz - 1, pch_skylake - 1, coretemp - Package id 0, coretemp - Core 0, coretemp - Core 1, iwlwifi_1 - 1)
GNOME Shell-INFO: 13:02:02.883: syncthing-indicator-manager: found config 127.0.0.1:8384 jRvPbPkXskeYYwhSPiX9TgU5HU3qcvbP https://127.0.0.1:8384
(gnome-shell:19687): GNOME Shell-DEBUG: 13:02:02.904: syncthing-indicator-manager: calling systemd is-enabled false systemctl,is-enabled,syncthing@alfredo disabled
(gnome-shell:19687): GNOME Shell-DEBUG: 13:02:02.924: syncthing-indicator-manager: calling systemd is-enabled true systemctl,is-enabled,syncthing,--user enabled
(gnome-shell:19687): GNOME Shell-DEBUG: 13:02:02.940: syncthing-indicator-manager: calling systemd is-active true systemctl,is-active,syncthing,--user active
(gnome-shell:19687): GNOME Shell-DEBUG: 13:02:02.940: syncthing-indicator-manager: service active true true false
(gnome-shell:19687): GNOME Shell-DEBUG: 13:02:02.942: syncthing-indicator-manager: opening connection GET:/rest/system/status
(gnome-shell:19687): GNOME Shell-DEBUG: 13:02:02.965: syncthing-indicator-manager: calling systemd is-enabled false systemctl,is-enabled,syncthing@alfredo disabled
(gnome-shell:19687): GNOME Shell-DEBUG: 13:02:02.982: syncthing-indicator-manager: calling systemd is-enabled true systemctl,is-enabled,syncthing,--user enabled
(gnome-shell:19687): GNOME Shell-DEBUG: 13:02:02.998: syncthing-indicator-manager: calling systemd is-active true systemctl,is-active,syncthing,--user active
(gnome-shell:19687): GNOME Shell-DEBUG: 13:02:02.998: syncthing-indicator-manager: service active true true true
(gnome-shell:19687): GNOME Shell-DEBUG: 13:02:02.998: syncthing-indicator-manager: opening connection GET:/rest/system/config
(gnome-shell:19687): GNOME Shell-DEBUG: 13:02:03.019: syncthing-indicator-manager: calling systemd is-enabled false systemctl,is-enabled,syncthing@alfredo disabled
(gnome-shell:19687): GNOME Shell-DEBUG: 13:02:03.034: syncthing-indicator-manager: calling systemd is-enabled true systemctl,is-enabled,syncthing,--user enabled
(gnome-shell:19687): GNOME Shell-DEBUG: 13:02:03.034: syncthing-indicator-manager: service enabled true true false

(gnome-shell:19687): GLib-GObject-CRITICAL **: 13:02:03.035: g_signal_handler_disconnect: assertion 'handler_id > 0' failed

(gnome-shell:19687): GLib-GObject-CRITICAL **: 13:02:03.035: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
(gnome-shell:19687): GNOME Shell-DEBUG: 13:02:03.035: syncthing-indicator-manager: opening connection GET:/rest/system/connections
(gnome-shell:19687): GNOME Shell-DEBUG: 13:02:03.035: syncthing-indicator-manager: opening connection GET:/rest/system/error
(gnome-shell:19687): GNOME Shell-DEBUG: 13:02:03.036: syncthing-indicator-manager: opening connection GET:/rest/system/error

(gnome-shell:19687): GNOME Shell-CRITICAL **: 13:02:03.316: syncthing-indicator-manager: Connection status error null GET:/rest/system/status 0

(gnome-shell:19687): GNOME Shell-CRITICAL **: 13:02:03.317: syncthing-indicator: connection-error {
    "type": "Connection status error",
    "message": "null - GET:/rest/system/status"
}

(gnome-shell:19687): GNOME Shell-WARNING **: 13:02:03.317: error: Syncthing Indicator: connection-error

(gnome-shell:19687): libmutter-WARNING **: 13:02:03.602: (../src/backends/meta-barrier.c:283):init_barrier_impl: runtime check failed: (priv->impl)

(gnome-shell:19687): libmutter-WARNING **: 13:02:03.602: (../src/backends/meta-barrier.c:283):init_barrier_impl: runtime check failed: (priv->impl)

(gnome-shell:19687): libmutter-WARNING **: 13:02:03.602: (../src/backends/meta-barrier.c:283):init_barrier_impl: runtime check failed: (priv->impl)

(gnome-shell:19687): GNOME Shell-CRITICAL **: 13:02:03.709: syncthing-indicator-manager: Connection status error null GET:/rest/system/config 0

(gnome-shell:19687): GNOME Shell-CRITICAL **: 13:02:03.710: syncthing-indicator: connection-error {
    "type": "Connection status error",
    "message": "null - GET:/rest/system/config"
}

(gnome-shell:19687): GNOME Shell-WARNING **: 13:02:03.710: error: Syncthing Indicator: connection-error

(gnome-shell:19687): GNOME Shell-CRITICAL **: 13:02:03.853: syncthing-indicator-manager: Connection status error null GET:/rest/system/connections 0

(gnome-shell:19687): GNOME Shell-CRITICAL **: 13:02:03.853: syncthing-indicator: connection-error {
    "type": "Connection status error",
    "message": "null - GET:/rest/system/connections"
}

(gnome-shell:19687): GNOME Shell-WARNING **: 13:02:03.854: error: Syncthing Indicator: connection-error

(gnome-shell:19687): GNOME Shell-CRITICAL **: 13:02:04.007: syncthing-indicator-manager: Connection status error null GET:/rest/system/error 0

(gnome-shell:19687): GNOME Shell-CRITICAL **: 13:02:04.007: syncthing-indicator: connection-error {
    "type": "Connection status error",
    "message": "null - GET:/rest/system/error"
}

(gnome-shell:19687): GNOME Shell-WARNING **: 13:02:04.008: error: Syncthing Indicator: connection-error
GNOME Shell-Message: 13:02:04.100: GNOME Shell started at Tue Apr 01 2025 13:02:01 GMT+0200 (hora de verano de Europa central)
GNOME Shell-Message: 13:02:04.100: Registering session with GDM

(gnome-shell:19687): GNOME Shell-CRITICAL **: 13:02:04.165: syncthing-indicator-manager: Connection status error null GET:/rest/system/error 0

(gnome-shell:19687): GNOME Shell-CRITICAL **: 13:02:04.166: syncthing-indicator: connection-error {
    "type": "Connection status error",
    "message": "null - GET:/rest/system/error"
}

(gnome-shell:19687): GNOME Shell-WARNING **: 13:02:04.166: error: Syncthing Indicator: connection-error
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported high keycode 256 for name <I256> ignored
>                   X11 cannot support keycodes above 255.
>                   This warning only shows for the first high keycode.
> Internal error:   Could not resolve keysym XF86AudioPreset
> Internal error:   Could not resolve keysym XF86Keyboard
> Internal error:   Could not resolve keysym XF86MonBrightnessCycle
> Internal error:   Could not resolve keysym XF86BrightnessAuto
> Internal error:   Could not resolve keysym XF86DisplayOff
> Internal error:   Could not resolve keysym XF86WWAN
> Internal error:   Could not resolve keysym XF86RFKill
> Internal error:   Could not resolve keysym XF86Info
> Internal error:   Could not resolve keysym XF86FullScreen
> Internal error:   Could not resolve keysym XF86AspectRatio
> Internal error:   Could not resolve keysym XF86DVD
> Internal error:   Could not resolve keysym XF86Audio
> Internal error:   Could not resolve keysym XF86ChannelUp
> Internal error:   Could not resolve keysym XF86ChannelDown
> Internal error:   Could not resolve keysym XF86Break
> Internal error:   Could not resolve keysym XF86VideoPhone
> Internal error:   Could not resolve keysym XF86ZoomReset
> Internal error:   Could not resolve keysym XF86Editor
> Internal error:   Could not resolve keysym XF86GraphicsEditor
> Internal error:   Could not resolve keysym XF86Presentation
> Internal error:   Could not resolve keysym XF86Database
> Internal error:   Could not resolve keysym XF86Voicemail
> Internal error:   Could not resolve keysym XF86Addressbook
> Internal error:   Could not resolve keysym XF86DisplayToggle
> Internal error:   Could not resolve keysym XF86SpellCheck
> Internal error:   Could not resolve keysym XF86ContextMenu
> Internal error:   Could not resolve keysym XF86MediaRepeat
> Internal error:   Could not resolve keysym XF8610ChannelsUp
> Internal error:   Could not resolve keysym XF8610ChannelsDown
> Internal error:   Could not resolve keysym XF86Images
> Internal error:   Could not resolve keysym XF86NotificationCenter
> Internal error:   Could not resolve keysym XF86PickupPhone
> Internal error:   Could not resolve keysym XF86HangupPhone
> Internal error:   Could not resolve keysym XF86Fn
> Internal error:   Could not resolve keysym XF86Fn_Esc
> Internal error:   Could not resolve keysym XF86FnRightShift
> Internal error:   Could not resolve keysym XF86Numeric0
> Internal error:   Could not resolve keysym XF86Numeric1
> Internal error:   Could not resolve keysym XF86Numeric2
> Internal error:   Could not resolve keysym XF86Numeric3
> Internal error:   Could not resolve keysym XF86Numeric4
> Internal error:   Could not resolve keysym XF86Numeric5
> Internal error:   Could not resolve keysym XF86Numeric6
> Internal error:   Could not resolve keysym XF86Numeric7
> Internal error:   Could not resolve keysym XF86Numeric8
> Internal error:   Could not resolve keysym XF86Numeric9
> Internal error:   Could not resolve keysym XF86NumericStar
> Internal error:   Could not resolve keysym XF86NumericPound
> Internal error:   Could not resolve keysym XF86NumericA
> Internal error:   Could not resolve keysym XF86NumericB
> Internal error:   Could not resolve keysym XF86NumericC
> Internal error:   Could not resolve keysym XF86NumericD
> Internal error:   Could not resolve keysym XF86CameraFocus
> Internal error:   Could not resolve keysym XF86WPSButton
> Internal error:   Could not resolve keysym XF86CameraZoomIn
> Internal error:   Could not resolve keysym XF86CameraZoomOut
> Internal error:   Could not resolve keysym XF86CameraUp
> Internal error:   Could not resolve keysym XF86CameraDown
> Internal error:   Could not resolve keysym XF86CameraLeft
> Internal error:   Could not resolve keysym XF86CameraRight
> Internal error:   Could not resolve keysym XF86AttendantOn
> Internal error:   Could not resolve keysym XF86AttendantOff
> Internal error:   Could not resolve keysym XF86AttendantToggle
> Internal error:   Could not resolve keysym XF86LightsToggle
> Internal error:   Could not resolve keysym XF86ALSToggle
> Internal error:   Could not resolve keysym XF86RotationLockToggle
> Internal error:   Could not resolve keysym XF86Buttonconfig
> Internal error:   Could not resolve keysym XF86Taskmanager
> Internal error:   Could not resolve keysym XF86Journal
> Internal error:   Could not resolve keysym XF86ControlPanel
> Internal error:   Could not resolve keysym XF86AppSelect
> Internal error:   Could not resolve keysym XF86Screensaver
> Internal error:   Could not resolve keysym XF86VoiceCommand
> Internal error:   Could not resolve keysym XF86Assistant
> Internal error:   Could not resolve keysym XF86EmojiPicker
> Internal error:   Could not resolve keysym XF86Dictate
> Internal error:   Could not resolve keysym XF86CameraAccessEnable
> Internal error:   Could not resolve keysym XF86CameraAccessDisable
> Internal error:   Could not resolve keysym XF86CameraAccessToggle
> Internal error:   Could not resolve keysym XF86BrightnessMin
> Internal error:   Could not resolve keysym XF86BrightnessMax
> Internal error:   Could not resolve keysym XF86KbdInputAssistPrev
> Internal error:   Could not resolve keysym XF86KbdInputAssistNext
> Internal error:   Could not resolve keysym XF86KbdInputAssistPrevgroup
> Internal error:   Could not resolve keysym XF86KbdInputAssistNextgroup
> Internal error:   Could not resolve keysym XF86KbdInputAssistAccept
> Internal error:   Could not resolve keysym XF86KbdInputAssistCancel
> Internal error:   Could not resolve keysym XF86RightUp
> Internal error:   Could not resolve keysym XF86RightDown
> Internal error:   Could not resolve keysym XF86LeftUp
> Internal error:   Could not resolve keysym XF86LeftDown
> Internal error:   Could not resolve keysym XF86RootMenu
> Internal error:   Could not resolve keysym XF86MediaTopMenu
> Internal error:   Could not resolve keysym XF86Numeric11
> Internal error:   Could not resolve keysym XF86Numeric12
> Internal error:   Could not resolve keysym XF86AudioDesc
> Internal error:   Could not resolve keysym XF863DMode
> Internal error:   Could not resolve keysym XF86NextFavorite
> Internal error:   Could not resolve keysym XF86StopRecord
> Internal error:   Could not resolve keysym XF86PauseRecord
> Internal error:   Could not resolve keysym XF86VOD
> Internal error:   Could not resolve keysym XF86Unmute
> Internal error:   Could not resolve keysym XF86FastReverse
> Internal error:   Could not resolve keysym XF86SlowReverse
> Internal error:   Could not resolve keysym XF86Data
> Internal error:   Could not resolve keysym XF86OnScreenKeyboard
> Internal error:   Could not resolve keysym XF86PrivacyScreenToggle
> Internal error:   Could not resolve keysym XF86SelectiveScreenshot
> Internal error:   Could not resolve keysym XF86NextElement
> Internal error:   Could not resolve keysym XF86PreviousElement
> Internal error:   Could not resolve keysym XF86AutopilotEngageToggle
> Internal error:   Could not resolve keysym XF86MarkWaypoint
> Internal error:   Could not resolve keysym XF86Sos
> Internal error:   Could not resolve keysym XF86NavChart
> Internal error:   Could not resolve keysym XF86FishingChart
> Internal error:   Could not resolve keysym XF86SingleRangeRadar
> Internal error:   Could not resolve keysym XF86DualRangeRadar
> Internal error:   Could not resolve keysym XF86RadarOverlay
> Internal error:   Could not resolve keysym XF86TraditionalSonar
> Internal error:   Could not resolve keysym XF86ClearvuSonar
> Internal error:   Could not resolve keysym XF86SidevuSonar
> Internal error:   Could not resolve keysym XF86NavInfo
> Internal error:   Could not resolve keysym XF86Macro1
> Internal error:   Could not resolve keysym XF86Macro2
> Internal error:   Could not resolve keysym XF86Macro3
> Internal error:   Could not resolve keysym XF86Macro4
> Internal error:   Could not resolve keysym XF86Macro5
> Internal error:   Could not resolve keysym XF86Macro6
> Internal error:   Could not resolve keysym XF86Macro7
> Internal error:   Could not resolve keysym XF86Macro8
> Internal error:   Could not resolve keysym XF86Macro9
> Internal error:   Could not resolve keysym XF86Macro10
> Internal error:   Could not resolve keysym XF86Macro11
> Internal error:   Could not resolve keysym XF86Macro12
> Internal error:   Could not resolve keysym XF86Macro13
> Internal error:   Could not resolve keysym XF86Macro14
> Internal error:   Could not resolve keysym XF86Macro15
> Internal error:   Could not resolve keysym XF86Macro16
> Internal error:   Could not resolve keysym XF86Macro17
> Internal error:   Could not resolve keysym XF86Macro18
> Internal error:   Could not resolve keysym XF86Macro19
> Internal error:   Could not resolve keysym XF86Macro20
> Internal error:   Could not resolve keysym XF86Macro21
> Internal error:   Could not resolve keysym XF86Macro22
> Internal error:   Could not resolve keysym XF86Macro23
> Internal error:   Could not resolve keysym XF86Macro24
> Internal error:   Could not resolve keysym XF86Macro25
> Internal error:   Could not resolve keysym XF86Macro26
> Internal error:   Could not resolve keysym XF86Macro27
> Internal error:   Could not resolve keysym XF86Macro28
> Internal error:   Could not resolve keysym XF86Macro29
> Internal error:   Could not resolve keysym XF86Macro30
> Internal error:   Could not resolve keysym XF86MacroRecordStart
> Internal error:   Could not resolve keysym XF86MacroRecordStop
> Internal error:   Could not resolve keysym XF86MacroPresetCycle
> Internal error:   Could not resolve keysym XF86MacroPreset1
> Internal error:   Could not resolve keysym XF86MacroPreset2
> Internal error:   Could not resolve keysym XF86MacroPreset3
> Internal error:   Could not resolve keysym XF86KbdLcdMenu1
> Internal error:   Could not resolve keysym XF86KbdLcdMenu2
> Internal error:   Could not resolve keysym XF86KbdLcdMenu3
> Internal error:   Could not resolve keysym XF86KbdLcdMenu4
> Internal error:   Could not resolve keysym XF86KbdLcdMenu5
Errors from xkbcomp are not fatal to the X server
dbus-daemon[19686]: [session uid=1000 pid=19686] Activating service name='org.freedesktop.systemd1' requested by ':1.0' (uid=1000 pid=19687 comm="gnome-shell --nested --wayland ")
dbus-daemon[20837]: writing oom_score_adj error: Permission denied
dbus-daemon[19686]: [session uid=1000 pid=19686] Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1

** (gnome-shell:19687): WARNING **: 13:02:12.704: Could not issue 'GetUnit' systemd call

** (gnome-shell:19687): WARNING **: 13:02:12.704: Could not issue 'StartUnit' systemd call
GNOME Shell-Message: 13:02:12.707: Error starting X11 services: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.freedesktop.systemd1 exited with status 1

(gnome-shell:19687): libmutter-WARNING **: 13:02:12.707: Failed to initialize X11 display: Unknown error

**Comment by alfredo-igm** [comment]
On Xorg :

dbus-daemon[5690]: [session uid=1000 pid=5690] Activating service name='org.gtk.vfs.Daemon' requested by ':1.0' (uid=1000 pid=5691 comm="gnome-shell --nested --wayland ")
dbus-daemon[5697]: writing oom_score_adj error: Permission denied
dbus-daemon[5690]: [session uid=1000 pid=5690] Successfully activated service 'org.gtk.vfs.Daemon'
fusermount3: failed to access mountpoint /run/user/1000/gvfs: Permission denied
libmutter-Message: 13:09:45.482: Running GNOME Shell (using mutter 45.3) as a Wayland display server
** Message: 13:09:45.661: Obtained a high priority EGL context
** Message: 13:09:45.663: Obtained a high priority EGL context
libmutter-Message: 13:09:46.065: Using public X11 display :1, (using :2 for managed services)
libmutter-Message: 13:09:46.065: Using Wayland display name 'wayland-0'
Window manager warning: Failed to set environment variable GNOME_SETUP_DISPLAY for gnome-session: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.gnome.SessionManager" does not exist
Window manager warning: Failed to set environment variable DISPLAY for gnome-session: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.gnome.SessionManager" does not exist
Window manager warning: Failed to set environment variable XAUTHORITY for gnome-session: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.gnome.SessionManager" does not exist
Window manager warning: Failed to set environment variable WAYLAND_DISPLAY for gnome-session: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.gnome.SessionManager" does not exist
GNOME Shell-Message: 13:09:46.729: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
GNOME Shell-Message: 13:09:46.730: Will monitor session 5
dbus-daemon[5690]: [session uid=1000 pid=5690] Activating service name='org.gnome.Shell.Screencast' requested by ':1.0' (uid=1000 pid=5691 comm="gnome-shell --nested --wayland ")
dbus-daemon[5734]: writing oom_score_adj error: Permission denied
dbus-daemon[5690]: [session uid=1000 pid=5690] Activating service name='org.freedesktop.impl.portal.PermissionStore' requested by ':1.0' (uid=1000 pid=5691 comm="gnome-shell --nested --wayland ")
dbus-daemon[5690]: [session uid=1000 pid=5690] Activating service name='org.gnome.Shell.CalendarServer' requested by ':1.0' (uid=1000 pid=5691 comm="gnome-shell --nested --wayland ")
dbus-daemon[5750]: writing oom_score_adj error: Permission denied
dbus-daemon[5749]: writing oom_score_adj error: Permission denied
dbus-daemon[5690]: [session uid=1000 pid=5690] Activating service name='org.gnome.evolution.dataserver.Sources5' requested by ':1.3' (uid=1000 pid=5750 comm="/usr/lib/gnome-shell/gnome-shell-calendar-server ")
(/usr/lib/xdg-permission-store:5749): GLib-GIO-DEBUG: 13:09:46.889: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
(/usr/lib/xdg-permission-store:5749): xdg-desktop-portal-DEBUG: 13:09:46.903: Starting permission store
dbus-daemon[5761]: writing oom_score_adj error: Permission denied
dbus-daemon[5690]: [session uid=1000 pid=5690] Successfully activated service 'org.freedesktop.impl.portal.PermissionStore'
dbus-daemon[5690]: [session uid=1000 pid=5690] Activating service name='org.gnome.Shell.Notifications' requested by ':1.0' (uid=1000 pid=5691 comm="gnome-shell --nested --wayland ")
GNOME Shell-Message: 13:09:47.026: Extension apps-menu@gnome-shell-extensions.gcampax.github.com already installed in /home/alfredo/.local/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com will not be loaded
GNOME Shell-Message: 13:09:47.027: Extension launch-new-instance@gnome-shell-extensions.gcampax.github.com already installed in /home/alfredo/.local/share/gnome-shell/extensions/launch-new-instance@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/launch-new-instance@gnome-shell-extensions.gcampax.github.com will not be loaded
GNOME Shell-Message: 13:09:47.027: Extension places-menu@gnome-shell-extensions.gcampax.github.com already installed in /home/alfredo/.local/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com will not be loaded
GNOME Shell-Message: 13:09:47.028: Extension window-list@gnome-shell-extensions.gcampax.github.com already installed in /home/alfredo/.local/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com will not be loaded
GNOME Shell-Message: 13:09:47.028: Extension workspace-indicator@gnome-shell-extensions.gcampax.github.com already installed in /home/alfredo/.local/share/gnome-shell/extensions/workspace-indicator@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/workspace-indicator@gnome-shell-extensions.gcampax.github.com will not be loaded
dbus-daemon[5771]: writing oom_score_adj error: Permission denied
dbus-daemon[5690]: [session uid=1000 pid=5690] Activating service name='org.gnome.OnlineAccounts' requested by ':1.5' (uid=1000 pid=5761 comm="/usr/lib/evolution-data-server/evolution-source-re")
dbus-daemon[5793]: writing oom_score_adj error: Permission denied
dbus-daemon[5690]: [session uid=1000 pid=5690] Successfully activated service 'org.gnome.evolution.dataserver.Sources5'
dbus-daemon[5690]: [session uid=1000 pid=5690] Successfully activated service 'org.gnome.Shell.Notifications'
dbus-daemon[5690]: [session uid=1000 pid=5690] Successfully activated service 'org.gnome.Shell.CalendarServer'
dbus-daemon[5690]: [session uid=1000 pid=5690] Activating service name='org.gnome.evolution.dataserver.Calendar8' requested by ':1.3' (uid=1000 pid=5750 comm="/usr/lib/gnome-shell/gnome-shell-calendar-server ")
dbus-daemon[5802]: writing oom_score_adj error: Permission denied
goa-daemon-Message: 13:09:47.233: goa-daemon version 3.48.0 starting
dbus-daemon[5690]: [session uid=1000 pid=5690] Activating service name='org.gnome.Identity' requested by ':1.7' (uid=1000 pid=5793 comm="/usr/lib/goa-daemon ")
dbus-daemon[5690]: [session uid=1000 pid=5690] Successfully activated service 'org.gnome.OnlineAccounts'
dbus-daemon[5813]: writing oom_score_adj error: Permission denied
dbus-daemon[5690]: [session uid=1000 pid=5690] Successfully activated service 'org.gnome.Identity'

(process:5813): libgoaidentity-WARNING **: 13:09:47.277: GoaKerberosIdentityManager: Using polling for change notification for credential cache type 'KEYRING'
dbus-daemon[5690]: [session uid=1000 pid=5690] Successfully activated service 'org.gnome.evolution.dataserver.Calendar8'
dbus-daemon[5690]: [session uid=1000 pid=5690] Activating service name='org.gnome.evolution.dataserver.AddressBook10' requested by ':1.8' (uid=1000 pid=5802 comm="/usr/lib/evolution-data-server/evolution-calendar-")
dbus-daemon[5826]: writing oom_score_adj error: Permission denied
dbus-daemon[5690]: [session uid=1000 pid=5690] Successfully activated service 'org.gnome.evolution.dataserver.AddressBook10'
GNOME Shell-Message: 13:09:47.500: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
dbus-daemon[5690]: [session uid=1000 pid=5690] Activating service name='org.gtk.vfs.UDisks2VolumeMonitor' requested by ':1.0' (uid=1000 pid=5691 comm="gnome-shell --nested --wayland ")
dbus-daemon[5850]: writing oom_score_adj error: Permission denied
dbus-daemon[5690]: [session uid=1000 pid=5690] Successfully activated service 'org.gtk.vfs.UDisks2VolumeMonitor'
dbus-daemon[5690]: [session uid=1000 pid=5690] Activating service name='org.gtk.vfs.AfcVolumeMonitor' requested by ':1.0' (uid=1000 pid=5691 comm="gnome-shell --nested --wayland ")
dbus-daemon[5860]: writing oom_score_adj error: Permission denied
dbus-daemon[5690]: [session uid=1000 pid=5690] Successfully activated service 'org.gtk.vfs.AfcVolumeMonitor'
dbus-daemon[5690]: [session uid=1000 pid=5690] Activating service name='org.gtk.vfs.GoaVolumeMonitor' requested by ':1.0' (uid=1000 pid=5691 comm="gnome-shell --nested --wayland ")
dbus-daemon[5867]: writing oom_score_adj error: Permission denied
dbus-daemon[5690]: [session uid=1000 pid=5690] Successfully activated service 'org.gtk.vfs.GoaVolumeMonitor'
dbus-daemon[5690]: [session uid=1000 pid=5690] Activating service name='org.gtk.vfs.MTPVolumeMonitor' requested by ':1.0' (uid=1000 pid=5691 comm="gnome-shell --nested --wayland ")
dbus-daemon[5873]: writing oom_score_adj error: Permission denied
dbus-daemon[5690]: [session uid=1000 pid=5690] Successfully activated service 'org.gtk.vfs.MTPVolumeMonitor'
dbus-daemon[5690]: [session uid=1000 pid=5690] Activating service name='org.gtk.vfs.GPhoto2VolumeMonitor' requested by ':1.0' (uid=1000 pid=5691 comm="gnome-shell --nested --wayland ")
dbus-daemon[5879]: writing oom_score_adj error: Permission denied
dbus-daemon[5690]: [session uid=1000 pid=5690] Successfully activated service 'org.gtk.vfs.GPhoto2VolumeMonitor'
GNOME Shell-Message: 13:09:47.706: Failed to register AuthenticationAgent
GNOME Shell-Message: 13:09:48.397: [system-monitor-next] applet enable from /home/alfredo/.local/share/gnome-shell/extensions/system-monitor-next@paradoxxx.zero.gmail.com

(gnome-shell:5691): GNOME Shell-CRITICAL **: 13:09:48.535: [system-monitor-next] Invalid thermal sensor label: "" (valid choices: acpitz - 1, pch_skylake - 1, coretemp - Package id 0, coretemp - Core 0, coretemp - Core 1, iwlwifi_1 - 1)
dbus-daemon[5690]: [session uid=1000 pid=5690] Successfully activated service 'org.gnome.Shell.Screencast'

(gnome-shell:5691): libmutter-WARNING **: 13:09:48.991: (../src/backends/meta-barrier.c:283):init_barrier_impl: runtime check failed: (priv->impl)

(gnome-shell:5691): libmutter-WARNING **: 13:09:48.991: (../src/backends/meta-barrier.c:283):init_barrier_impl: runtime check failed: (priv->impl)

(gnome-shell:5691): libmutter-WARNING **: 13:09:48.991: (../src/backends/meta-barrier.c:283):init_barrier_impl: runtime check failed: (priv->impl)
GNOME Shell-Message: 13:09:49.634: GNOME Shell started at Tue Apr 01 2025 13:09:47 GMT+0200 (hora de verano de Europa central)
GNOME Shell-Message: 13:09:49.635: Registering session with GDM

(gnome-shell:5691): GLib-CRITICAL **: 13:09:56.474: Source ID 3530 was not found when attempting to remove it

(gnome-shell:5691): GLib-CRITICAL **: 13:09:56.524: Source ID 3537 was not found when attempting to remove it

(gnome-shell:5691): GLib-CRITICAL **: 13:09:56.567: Source ID 3551 was not found when attempting to remove it

(gnome-shell:5691): GLib-CRITICAL **: 13:09:56.575: Source ID 3553 was not found when attempting to remove it

(gnome-shell:5691): GLib-CRITICAL **: 13:09:56.591: Source ID 3556 was not found when attempting to remove it

(gnome-shell:5691): GLib-CRITICAL **: 13:10:04.306: Source ID 4070 was not found when attempting to remove it

(gnome-shell:5691): GLib-CRITICAL **: 13:10:04.339: Source ID 4079 was not found when attempting to remove it

(gnome-shell:5691): GLib-CRITICAL **: 13:10:07.672: Source ID 4312 was not found when attempting to remove it

(gnome-shell:5691): GLib-CRITICAL **: 13:10:07.676: Source ID 4316 was not found when attempting to remove it

(gnome-shell:5691): GLib-CRITICAL **: 13:10:07.705: Source ID 4321 was not found when attempting to remove it

(gnome-shell:5691): GLib-CRITICAL **: 13:10:07.722: Source ID 4328 was not found when attempting to remove it

(gnome-shell:5691): GLib-CRITICAL **: 13:10:07.738: Source ID 4331 was not found when attempting to remove it

(gnome-shell:5691): GLib-CRITICAL **: 13:10:07.754: Source ID 4338 was not found when attempting to remove it

(gnome-shell:5691): GLib-CRITICAL **: 13:10:07.771: Source ID 4341 was not found when attempting to remove it

(gnome-shell:5691): GLib-CRITICAL **: 13:10:07.788: Source ID 4348 was not found when attempting to remove it

(gnome-shell:5691): GLib-CRITICAL **: 13:10:07.805: Source ID 4353 was not found when attempting to remove it

(gnome-shell:5691): GLib-CRITICAL **: 13:10:08.382: Source ID 4358 was not found when attempting to remove it

(gnome-shell:5691): GLib-CRITICAL **: 13:10:08.390: Source ID 4373 was not found when attempting to remove it

(gnome-shell:5691): GLib-CRITICAL **: 13:10:08.398: Source ID 4377 was not found when attempting to remove it

(gnome-shell:5691): GLib-CRITICAL **: 13:10:08.406: Source ID 4381 was not found when attempting to remove it

(gnome-shell:5691): GLib-CRITICAL **: 13:10:08.419: Source ID 4385 was not found when attempting to remove it

(gnome-shell:5691): GLib-CRITICAL **: 13:10:08.432: Source ID 4390 was not found when attempting to remove it

(gnome-shell:5691): GLib-CRITICAL **: 13:10:08.438: Source ID 4393 was not found when attempting to remove it

(gnome-shell:5691): GLib-CRITICAL **: 13:10:08.455: Source ID 4397 was not found when attempting to remove it

(gnome-shell:5691): GLib-CRITICAL **: 13:10:08.510: Source ID 4404 was not found when attempting to remove it

(gnome-shell:5691): GLib-CRITICAL **: 13:10:08.686: Source ID 4409 was not found when attempting to remove it

(gnome-shell:5691): GLib-CRITICAL **: 13:10:08.798: Source ID 4413 was not found when attempting to remove it

(gnome-shell:5691): GLib-CRITICAL **: 13:10:08.950: Source ID 4418 was not found when attempting to remove it

(gnome-shell:5691): GLib-CRITICAL **: 13:10:08.998: Source ID 4425 was not found when attempting to remove it

(gnome-shell:5691): GLib-CRITICAL **: 13:10:09.015: Source ID 4430 was not found when attempting to remove it

(gnome-shell:5691): GLib-CRITICAL **: 13:10:09.038: Source ID 4434 was not found when attempting to remove it

(gnome-shell:5691): GLib-CRITICAL **: 13:10:09.047: Source ID 4438 was not found when attempting to remove it

(gnome-shell:5691): GLib-CRITICAL **: 13:10:09.054: Source ID 4442 was not found when attempting to remove it

(gnome-shell:5691): GLib-CRITICAL **: 13:10:09.094: Source ID 4450 was not found when attempting to remove it

(gnome-shell:5691): GLib-CRITICAL **: 13:10:09.105: Source ID 4454 was not found when attempting to remove it

(gnome-shell:5691): GLib-CRITICAL **: 13:10:09.121: Source ID 4457 was not found when attempting to remove it
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported high keycode 256 for name <I256> ignored
>                   X11 cannot support keycodes above 255.
>                   This warning only shows for the first high keycode.
> Internal error:   Could not resolve keysym XF86AudioPreset
> Internal error:   Could not resolve keysym XF86Keyboard
> Internal error:   Could not resolve keysym XF86MonBrightnessCycle
> Internal error:   Could not resolve keysym XF86BrightnessAuto
> Internal error:   Could not resolve keysym XF86DisplayOff
> Internal error:   Could not resolve keysym XF86WWAN
> Internal error:   Could not resolve keysym XF86RFKill
> Internal error:   Could not resolve keysym XF86Info
> Internal error:   Could not resolve keysym XF86FullScreen
> Internal error:   Could not resolve keysym XF86AspectRatio
> Internal error:   Could not resolve keysym XF86DVD
> Internal error:   Could not resolve keysym XF86Audio
> Internal error:   Could not resolve keysym XF86ChannelUp
> Internal error:   Could not resolve keysym XF86ChannelDown
> Internal error:   Could not resolve keysym XF86Break
> Internal error:   Could not resolve keysym XF86VideoPhone
> Internal error:   Could not resolve keysym XF86ZoomReset
> Internal error:   Could not resolve keysym XF86Editor
> Internal error:   Could not resolve keysym XF86GraphicsEditor
> Internal error:   Could not resolve keysym XF86Presentation
> Internal error:   Could not resolve keysym XF86Database
> Internal error:   Could not resolve keysym XF86Voicemail
> Internal error:   Could not resolve keysym XF86Addressbook
> Internal error:   Could not resolve keysym XF86DisplayToggle
> Internal error:   Could not resolve keysym XF86SpellCheck
> Internal error:   Could not resolve keysym XF86ContextMenu
> Internal error:   Could not resolve keysym XF86MediaRepeat
> Internal error:   Could not resolve keysym XF8610ChannelsUp
> Internal error:   Could not resolve keysym XF8610ChannelsDown
> Internal error:   Could not resolve keysym XF86Images
> Internal error:   Could not resolve keysym XF86NotificationCenter
> Internal error:   Could not resolve keysym XF86PickupPhone
> Internal error:   Could not resolve keysym XF86HangupPhone
> Internal error:   Could not resolve keysym XF86Fn
> Internal error:   Could not resolve keysym XF86Fn_Esc
> Internal error:   Could not resolve keysym XF86FnRightShift
> Internal error:   Could not resolve keysym XF86Numeric0
> Internal error:   Could not resolve keysym XF86Numeric1
> Internal error:   Could not resolve keysym XF86Numeric2
> Internal error:   Could not resolve keysym XF86Numeric3
> Internal error:   Could not resolve keysym XF86Numeric4
> Internal error:   Could not resolve keysym XF86Numeric5
> Internal error:   Could not resolve keysym XF86Numeric6
> Internal error:   Could not resolve keysym XF86Numeric7
> Internal error:   Could not resolve keysym XF86Numeric8
> Internal error:   Could not resolve keysym XF86Numeric9
> Internal error:   Could not resolve keysym XF86NumericStar
> Internal error:   Could not resolve keysym XF86NumericPound
> Internal error:   Could not resolve keysym XF86NumericA
> Internal error:   Could not resolve keysym XF86NumericB
> Internal error:   Could not resolve keysym XF86NumericC
> Internal error:   Could not resolve keysym XF86NumericD
> Internal error:   Could not resolve keysym XF86CameraFocus
> Internal error:   Could not resolve keysym XF86WPSButton
> Internal error:   Could not resolve keysym XF86CameraZoomIn
> Internal error:   Could not resolve keysym XF86CameraZoomOut
> Internal error:   Could not resolve keysym XF86CameraUp
> Internal error:   Could not resolve keysym XF86CameraDown
> Internal error:   Could not resolve keysym XF86CameraLeft
> Internal error:   Could not resolve keysym XF86CameraRight
> Internal error:   Could not resolve keysym XF86AttendantOn
> Internal error:   Could not resolve keysym XF86AttendantOff
> Internal error:   Could not resolve keysym XF86AttendantToggle
> Internal error:   Could not resolve keysym XF86LightsToggle
> Internal error:   Could not resolve keysym XF86ALSToggle
> Internal error:   Could not resolve keysym XF86RotationLockToggle
> Internal error:   Could not resolve keysym XF86Buttonconfig
> Internal error:   Could not resolve keysym XF86Taskmanager
> Internal error:   Could not resolve keysym XF86Journal
> Internal error:   Could not resolve keysym XF86ControlPanel
> Internal error:   Could not resolve keysym XF86AppSelect
> Internal error:   Could not resolve keysym XF86Screensaver
> Internal error:   Could not resolve keysym XF86VoiceCommand
> Internal error:   Could not resolve keysym XF86Assistant
> Internal error:   Could not resolve keysym XF86EmojiPicker
> Internal error:   Could not resolve keysym XF86Dictate
> Internal error:   Could not resolve keysym XF86CameraAccessEnable
> Internal error:   Could not resolve keysym XF86CameraAccessDisable
> Internal error:   Could not resolve keysym XF86CameraAccessToggle
> Internal error:   Could not resolve keysym XF86BrightnessMin
> Internal error:   Could not resolve keysym XF86BrightnessMax
> Internal error:   Could not resolve keysym XF86KbdInputAssistPrev
> Internal error:   Could not resolve keysym XF86KbdInputAssistNext
> Internal error:   Could not resolve keysym XF86KbdInputAssistPrevgroup
> Internal error:   Could not resolve keysym XF86KbdInputAssistNextgroup
> Internal error:   Could not resolve keysym XF86KbdInputAssistAccept
> Internal error:   Could not resolve keysym XF86KbdInputAssistCancel
> Internal error:   Could not resolve keysym XF86RightUp
> Internal error:   Could not resolve keysym XF86RightDown
> Internal error:   Could not resolve keysym XF86LeftUp
> Internal error:   Could not resolve keysym XF86LeftDown
> Internal error:   Could not resolve keysym XF86RootMenu
> Internal error:   Could not resolve keysym XF86MediaTopMenu
> Internal error:   Could not resolve keysym XF86Numeric11
> Internal error:   Could not resolve keysym XF86Numeric12
> Internal error:   Could not resolve keysym XF86AudioDesc
> Internal error:   Could not resolve keysym XF863DMode
> Internal error:   Could not resolve keysym XF86NextFavorite
> Internal error:   Could not resolve keysym XF86StopRecord
> Internal error:   Could not resolve keysym XF86PauseRecord
> Internal error:   Could not resolve keysym XF86VOD
> Internal error:   Could not resolve keysym XF86Unmute
> Internal error:   Could not resolve keysym XF86FastReverse
> Internal error:   Could not resolve keysym XF86SlowReverse
> Internal error:   Could not resolve keysym XF86Data
> Internal error:   Could not resolve keysym XF86OnScreenKeyboard
> Internal error:   Could not resolve keysym XF86PrivacyScreenToggle
> Internal error:   Could not resolve keysym XF86SelectiveScreenshot
> Internal error:   Could not resolve keysym XF86NextElement
> Internal error:   Could not resolve keysym XF86PreviousElement
> Internal error:   Could not resolve keysym XF86AutopilotEngageToggle
> Internal error:   Could not resolve keysym XF86MarkWaypoint
> Internal error:   Could not resolve keysym XF86Sos
> Internal error:   Could not resolve keysym XF86NavChart
> Internal error:   Could not resolve keysym XF86FishingChart
> Internal error:   Could not resolve keysym XF86SingleRangeRadar
> Internal error:   Could not resolve keysym XF86DualRangeRadar
> Internal error:   Could not resolve keysym XF86RadarOverlay
> Internal error:   Could not resolve keysym XF86TraditionalSonar
> Internal error:   Could not resolve keysym XF86ClearvuSonar
> Internal error:   Could not resolve keysym XF86SidevuSonar
> Internal error:   Could not resolve keysym XF86NavInfo
> Internal error:   Could not resolve keysym XF86Macro1
> Internal error:   Could not resolve keysym XF86Macro2
> Internal error:   Could not resolve keysym XF86Macro3
> Internal error:   Could not resolve keysym XF86Macro4
> Internal error:   Could not resolve keysym XF86Macro5
> Internal error:   Could not resolve keysym XF86Macro6
> Internal error:   Could not resolve keysym XF86Macro7
> Internal error:   Could not resolve keysym XF86Macro8
> Internal error:   Could not resolve keysym XF86Macro9
> Internal error:   Could not resolve keysym XF86Macro10
> Internal error:   Could not resolve keysym XF86Macro11
> Internal error:   Could not resolve keysym XF86Macro12
> Internal error:   Could not resolve keysym XF86Macro13
> Internal error:   Could not resolve keysym XF86Macro14
> Internal error:   Could not resolve keysym XF86Macro15
> Internal error:   Could not resolve keysym XF86Macro16
> Internal error:   Could not resolve keysym XF86Macro17
> Internal error:   Could not resolve keysym XF86Macro18
> Internal error:   Could not resolve keysym XF86Macro19
> Internal error:   Could not resolve keysym XF86Macro20
> Internal error:   Could not resolve keysym XF86Macro21
> Internal error:   Could not resolve keysym XF86Macro22
> Internal error:   Could not resolve keysym XF86Macro23
> Internal error:   Could not resolve keysym XF86Macro24
> Internal error:   Could not resolve keysym XF86Macro25
> Internal error:   Could not resolve keysym XF86Macro26
> Internal error:   Could not resolve keysym XF86Macro27
> Internal error:   Could not resolve keysym XF86Macro28
> Internal error:   Could not resolve keysym XF86Macro29
> Internal error:   Could not resolve keysym XF86Macro30
> Internal error:   Could not resolve keysym XF86MacroRecordStart
> Internal error:   Could not resolve keysym XF86MacroRecordStop
> Internal error:   Could not resolve keysym XF86MacroPresetCycle
> Internal error:   Could not resolve keysym XF86MacroPreset1
> Internal error:   Could not resolve keysym XF86MacroPreset2
> Internal error:   Could not resolve keysym XF86MacroPreset3
> Internal error:   Could not resolve keysym XF86KbdLcdMenu1
> Internal error:   Could not resolve keysym XF86KbdLcdMenu2
> Internal error:   Could not resolve keysym XF86KbdLcdMenu3
> Internal error:   Could not resolve keysym XF86KbdLcdMenu4
> Internal error:   Could not resolve keysym XF86KbdLcdMenu5
Errors from xkbcomp are not fatal to the X server
dbus-daemon[5690]: [session uid=1000 pid=5690] Activating service name='org.freedesktop.systemd1' requested by ':1.0' (uid=1000 pid=5691 comm="gnome-shell --nested --wayland ")
dbus-daemon[6135]: writing oom_score_adj error: Permission denied
dbus-daemon[5690]: [session uid=1000 pid=5690] Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1

** (gnome-shell:5691): WARNING **: 13:10:09.571: Could not issue 'GetUnit' systemd call

** (gnome-shell:5691): WARNING **: 13:10:09.572: Could not issue 'StartUnit' systemd call
GNOME Shell-Message: 13:10:09.573: Error starting X11 services: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.freedesktop.systemd1 exited with status 1

(gnome-shell:5691): libmutter-WARNING **: 13:10:09.574: Failed to initialize X11 display: Unknown error

(gnome-shell:5691): Clutter-WARNING **: 13:10:13.787: (../clutter/clutter/clutter-actor.c:11813):clutter_actor_event: runtime check failed: (retval == CLUTTER_EVENT_PROPAGATE)

(gnome-shell:5691): Clutter-WARNING **: 13:10:13.810: (../clutter/clutter/clutter-actor.c:11813):clutter_actor_event: runtime check failed: (retval == CLUTTER_EVENT_PROPAGATE)

(gnome-shell:5691): Clutter-WARNING **: 13:10:13.813: (../clutter/clutter/clutter-actor.c:11813):clutter_actor_event: runtime check failed: (retval == CLUTTER_EVENT_PROPAGATE)

(gnome-shell:5691): Clutter-WARNING **: 13:10:13.840: (../clutter/clutter/clutter-actor.c:11813):clutter_actor_event: runtime check failed: (retval == CLUTTER_EVENT_PROPAGATE)

(gnome-shell:5691): Clutter-WARNING **: 13:10:13.846: (../clutter/clutter/clutter-actor.c:11813):clutter_actor_event: runtime check failed: (retval == CLUTTER_EVENT_PROPAGATE)

(gnome-shell:5691): Clutter-WARNING **: 13:10:13.848: (../clutter/clutter/clutter-actor.c:11813):clutter_actor_event: runtime check failed: (retval == CLUTTER_EVENT_PROPAGATE)

(gnome-shell:5691): Clutter-WARNING **: 13:10:13.853: (../clutter/clutter/clutter-actor.c:11813):clutter_actor_event: runtime check failed: (retval == CLUTTER_EVENT_PROPAGATE)

(gnome-shell:5691): Clutter-WARNING **: 13:10:13.858: (../clutter/clutter/clutter-actor.c:11813):clutter_actor_event: runtime check failed: (retval == CLUTTER_EVENT_PROPAGATE)

(gnome-shell:5691): Clutter-WARNING **: 13:10:13.867: (../clutter/clutter/clutter-actor.c:11813):clutter_actor_event: runtime check failed: (retval == CLUTTER_EVENT_PROPAGATE)

(gnome-shell:5691): Clutter-WARNING **: 13:10:13.874: (../clutter/clutter/clutter-actor.c:11813):clutter_actor_event: runtime check failed: (retval == CLUTTER_EVENT_PROPAGATE)

(gnome-shell:5691): Clutter-WARNING **: 13:10:13.884: (../clutter/clutter/clutter-actor.c:11813):clutter_actor_event: runtime check failed: (retval == CLUTTER_EVENT_PROPAGATE)

(gnome-shell:5691): Clutter-WARNING **: 13:10:13.887: (../clutter/clutter/clutter-actor.c:11813):clutter_actor_event: runtime check failed: (retval == CLUTTER_EVENT_PROPAGATE)

(gnome-shell:5691): Clutter-WARNING **: 13:10:13.904: (../clutter/clutter/clutter-actor.c:11813):clutter_actor_event: runtime check failed: (retval == CLUTTER_EVENT_PROPAGATE)

(gnome-shell:5691): Clutter-WARNING **: 13:10:13.906: (../clutter/clutter/clutter-actor.c:11813):clutter_actor_event: runtime check failed: (retval == CLUTTER_EVENT_PROPAGATE)

(gnome-shell:5691): Clutter-WARNING **: 13:10:13.913: (../clutter/clutter/clutter-actor.c:11813):clutter_actor_event: runtime check failed: (retval == CLUTTER_EVENT_PROPAGATE)

(gnome-shell:5691): Clutter-WARNING **: 13:10:13.927: (../clutter/clutter/clutter-actor.c:11813):clutter_actor_event: runtime check failed: (retval == CLUTTER_EVENT_PROPAGATE)

(gnome-shell:5691): Clutter-WARNING **: 13:10:13.928: (../clutter/clutter/clutter-actor.c:11813):clutter_actor_event: runtime check failed: (retval == CLUTTER_EVENT_PROPAGATE)

(gnome-shell:5691): Clutter-WARNING **: 13:10:13.937: (../clutter/clutter/clutter-actor.c:11813):clutter_actor_event: runtime check failed: (retval == CLUTTER_EVENT_PROPAGATE)

(gnome-shell:5691): Clutter-WARNING **: 13:10:13.954: (../clutter/clutter/clutter-actor.c:11813):clutter_actor_event: runtime check failed: (retval == CLUTTER_EVENT_PROPAGATE)

(gnome-shell:5691): Clutter-WARNING **: 13:10:13.955: (../clutter/clutter/clutter-actor.c:11813):clutter_actor_event: runtime check failed: (retval == CLUTTER_EVENT_PROPAGATE)

(gnome-shell:5691): Clutter-WARNING **: 13:10:13.970: (../clutter/clutter/clutter-actor.c:11813):clutter_actor_event: runtime check failed: (retval == CLUTTER_EVENT_PROPAGATE)

(gnome-shell:5691): Clutter-WARNING **: 13:10:13.971: (../clutter/clutter/clutter-actor.c:11813):clutter_actor_event: runtime check failed: (retval == CLUTTER_EVENT_PROPAGATE)

(gnome-shell:5691): Clutter-WARNING **: 13:10:13.987: (../clutter/clutter/clutter-actor.c:11813):clutter_actor_event: runtime check failed: (retval == CLUTTER_EVENT_PROPAGATE)
dbus-daemon[5690]: [session uid=1000 pid=5690] Activating service name='org.gtk.vfs.Metadata' requested by ':1.0' (uid=1000 pid=5691 comm="gnome-shell --nested --wayland ")
dbus-daemon[9327]: writing oom_score_adj error: Permission denied
dbus-daemon[5690]: [session uid=1000 pid=5690] Successfully activated service 'org.gtk.vfs.Metadata'
^C

(goa-daemon:5793): GLib-GIO-WARNING **: 13:10:53.391: Error releasing name org.gnome.OnlineAccounts: La conexión está cerrada
goa-daemon-Message: 13:10:53.391: goa-daemon version 3.48.0 exiting

**Comment by alfredo-igm** [comment]
CONGRATULATIONS !!! 
YOU DID IT !!!
"Use TLS" was checked.
Unchecked and worrying notifications have gone.
Thank you VERY MUCH.
I'm curious. Which line of the log gave away the culprit?

**Comment by 2nv2u** [comment]
Nice! I started comparing your output with mine and noticed the "https" and remembered I fixed a self signed certificate issue before. After some investigation it turned out my fix did not work anymore since gnome shell changed to the Soup (http) lib.
As a bonus I fixed this again, so using TLS  should not be an issue anymore in the next version.
Thanks for helping debugging this!
